### PR TITLE
Adding possibility to overwrite the service endpoint while importing …

### PR DESCRIPTION
**Pull request by prakashmrec**
…Swagger definition into a Ready! API  project

### CODE REVIEW

**Comment by olensmar** [comment]
Does the Swagger2Importer have to do this? Can't the client using it simply update the endpoint after importing?

**Comment by prakashmrec** [comment]
Yes, client can also do it, but then client will have to iterate over all the requests and set endpoint for each one of them. This was simpler :) Also, we can allow users to overwrite endpoint in Ready! API as well if we want to.
But I can do it in client if you insist :)

**Comment by olensmar** [comment]
hehe - I think the SetEndpointAction in R!A actually has code that does this but I don't think it can be reused from here. Sorry - but I'm going to be a pain and ask you to move this the client - perhaps you can create a util class with a "setEndpointOnRequests" method!?

**Comment by prakashmrec** [comment]
That's ok. I will close this PR and do it in client then. Thanks.

**Pull request closed without merging**
