### PR TITLE
implementing the interface required to use the assertion in recipes

### PR DESCRIPTION
**Pull request by prakashmrec**

### CODE REVIEW

**Comment by prakashmrec** [comment]
@olensmar Did we move this assertion to Ready! API code base? if not - then we should merge this PR to be able to have this assertion in recipes.

**Comment by olensmar** [comment]
thanks - we only moved the JSON Schema Assertion to the R!A codebase - this one is staying in the plugin for now

**Comment by prakashmrec** [comment]
Sorry the build failed for this PR. I will fix it in a separate PR.

**Comment by olensmar** [comment]
i think the fail was related to Travis CI - or was it something that failed locally for you also?

**Comment by prakashmrec** [comment]
It failed locally also, it was missing a dependency for commons-collections. Probably it was available earlier through a transitive dependency but not anymore.

**Pull request merged**
